version: '3.3'

services:
  api:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: nodejs
    container_name: masterclass-sequelize_api
    ports:
      - "3334:3000"
    restart: always
    command: npm start
    volumes:
      - .:/usr/app
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres
    container_name: masterclass-sequelize_postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATA=/data/postgres
    volumes:
      - ./data/postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT}:5432"
